# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go
# SET UP GO
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


